export const questions = [
	'Donut',
	'Zombie',
	'Dancing a ballet',
	'Washing an elephant',
	'Rock climbing',
	'Shopping at the mall',
	'Playing soccer',
	'Flying a kite',
	'Going bowling',
	'Scuba diving',
	'Chasing a tornado',
	'Building a campfire',
	'Sewing a dress',
	'Filming a movie',
	'Riding a carousel',
	'Playing chess',
	'Finger painting',
	'Sewing on a button',
	'Ironing a shirt',
	'Baking bread',
	'Making a pizza',
	'Having a food fight',
	'Paddling in a canoe',
	'Delivering mail',
	'Riding a motorcycle',
	'Flipping pancakes',
	'Sorting laundry',
	'Playing hopscotch',
	'Hailing a taxi',
	'Landing an airplane',
	'Watering a garden',
	'Mowing a lawn',
	'Raking leaves',
	'Feeding the ducks',
	'Building a sandcastle',
	'Playing baseball',
	'Milking a cow',
	'Setting up a tent',
	'Whale watching',
	'Trick-or-treating',
	'Walking with crutches',
	'Riding in a chairlift',
	'Sumo wrestling',
	'Digging a hole',
	'Riding bumper cars',
	'Karate',
	'Hang-gliding',
	"Cutting someone's hair",
	'Swimming with dolphins',
	'Going through airport security',
	'Filling up a car with petrol',
	'Ordering food at a restaurant',
	'Operating a jackhammer',
	'Picking apples from a tree',
	'Gathering eggs from a hen house',
	'Watching a movie at the theater',
	'Climbing a mountain',
	'Going on an African safari',
	'Performing at a rock concert',
	'Piano',
	'Asking for an autograph',
	'Walking through a haunted house',
	'Opening birthday presents',
	'Body surfing at the beach',
	'Painting the walls in a room',
	'Being a flight attendant',
	'Washing windows on a building',
	'Kiss',
	'Windmill',
	'Party',
	'Dentist',
	'Lawn',
	'Mower',
	'Mermaid',
	'Wig',
	'Stain',
	'Cuff',
	'Sunburn',
	'Funny',
	'Sheet',
	'Hair',
	'Dryer',
	'Nightmare',
	'Shadow',
	'Wax',
	'Fog',
	'Sip',
	'Bathroom',
	'Scale',
	'Taxi',
	'Pizza',
	'Sand',
	'Huddle',
	'Cowboy',
	'Ticket',
	'Doghouse',
	'Stiff',
	'Knot',
	'President',
	'Owl',
	'Wrench',
	'Story',
	'Whisk',
	'Quicksand',
	'Spine',
	'Chess',
	'Artist',
	'Vest',
	'Gingerbread man',
	'Spider web',
	'Bobsled',
	'Lung',
	'Washing machine',
	'Oar',
	'Torch',
	'Eraser',
	'Mouse',
	'Trap',
	'Swordfish',
	'Jar',
	'Cramp',
	'Flamingo',
	'Cast',
	'Honk',
	'Mirror',
	'Chalk',
	'Gym',
	'Volcano',
	'Ping pong',
	'Snowball',
	'Fly',
	'Fang',
	'Bicycle',
	'Bear',
	'Cape',
	'Puppet',
	'Piano',
	'Lipstick',
	'Salute',
	'Hula hoop',
	'Penguin',
	'Banana',
	'Peel',
	'Whisper',
	'Popsicle',
	'Frankenstein',
	'Earthquake',
	'Yo-yo',
	'Road',
	'Rain',
	'Alarm',
	'Clock',
	'Dog',
	'Leash',
	'Chop',
	'Pyjamas',
	'Slam dunk',
	'Fiddle',
	'Seashell',
	'Jog',
	'Seesaw',
	'Nap',
	'Cheerleader',
	'Blind',
	'Beg',
	'Shopping',
	'Cart',
	'Limbo',
	'Newspaper',
	'Twist',
	'Rhinoceros',
	'Cow',
	'Tickle',
	'Fetch',
	'Violin',
	'Cage',
	'Cello',
	'Braid',
	'Skateboard',
	'Stairs',
	'Trumpet',
	'Mop',
	'Shovel',
	'Money',
	'Soap',
	'Saddle',
	'Wink',
	'Tree',
	'Spider Man',
	'Santa Claus',
	'Elves',
	'Sleigh ride',
	'Jingle bells',
	'Chimney',
	'Caroling',
	'Sherlock Holmes',
	'Me!',
	'Neil Armstrong'
];

export const getShuffledQuestions = () => {
	const array = [...questions];
	for (let i = array.length - 1; i > 0; i--) {
		let j = Math.floor(Math.random() * (i + 1));
		[array[i], array[j]] = [array[j], array[i]];
	}
	return array;
};
